name: deploy-nunchuk-macos

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install AppDmg
        working-directory: ${{runner.workspace}}
        run: |
          npm install -g appdmg
          
      - name: Download build output
        working-directory: ${{runner.workspace}}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          job_runs_id="14309372792"
          gh run download $job_runs_id -n "nunchuk-macos-built" --repo hadvluffy/macdeploynunchuk
          unzip nunchuk-macos-built.zip
          echo "ls -l"
          ls -l 

      - name: Create appdmg JSON configuration
        working-directory: ${{runner.workspace}}
        run: |
          cat <<EOF > dmg.json
          {
            "title": "nunchuk-macos",
            "background": "",
            "icon-size": 100,
            "window": {
              "size": [800, 400],
              "position": [200, 150]
            },
            "contents": [
              {
                "x": 200,
                "y": 200,
                "type": "file",
                "path": "nunchuk-macos-built/Nunchuk.app"
              },
              {
                "x": 600,
                "y": 200,
                "type": "link",
                "path": "/Applications"
              }
            ]
          }
          EOF
          ls -l
          
      - name: Create DMG
        working-directory: ${{runner.workspace}}
        run: |
          mkdir dist
          appdmg dmg.json dist/Nunchuk.dmg
          ls -l dist

      - name: Zip toàn bộ output dist
        working-directory: ${{runner.workspace}}
        run: |
          zip -r dist.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{runner.workspace}}/dist.zip
