name: deploy-hwi-release-flow

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout HWI
        working-directory: ${{runner.workspace}}
        run: |
          gh run download 13851885596 -n "deploy-hwi-download"
          ls -l 
