name: deploy-hwi-release-flow

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout HWI
        working-directory: ${{runner.workspace}}
        run: |
          wget -c -q "https://github.com/hadvluffy/macdeploynunchuk/actions/runs/13851885596/artifacts/2751027802" -O - | tar -xz
          ls -l 
