name: deploy-hwi-release-flow

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout HWI
        working-directory: ${{runner.workspace}}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh run download 13851885596 -n "dist_macos.zip" --repo hadvluffy/macdeploynunchuk
          ls -l 
