name: nunchuk-window-x86_64

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Check Windows Version
        shell: powershell
        run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Setup Cache vcpkg packages
        uses: actions/cache@v4
        with:
          path: ${{ runner.workspace }}/vcpkg
          key: vcpkg-full-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-full-${{ runner.os }}-

      - name: Set up vcpkg
        working-directory: ${{ runner.workspace }}
        shell: powershell
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          git checkout eb492805e92a2c14a230f5c3deb3e89f6771c321
          .\bootstrap-vcpkg.bat

      - name: Install dependencies with vcpkg
        working-directory: ${{ runner.workspace }}
        shell: powershell
        run: |
          vcpkg\vcpkg.exe install boost:x64-windows `
                                  zeromq:x64-windows `
                                  libevent:x64-windows `
                                  berkeleydb:x64-windows `
                                  sqlite3:x64-windows `
                                  sqlcipher:x64-windows `
                                  qt5:x64-windows `
                                  qt5-graphicaleffects:x64-windows `
                                  qt5-quickcontrols:x64-windows `
                                  qtKeychain:x64-windows
                        
          vcpkg\vcpkg.exe integrate install
          vcpkg\vcpkg.exe list
          
      - name: Clone Olm
        run: git clone https://gitlab.matrix.org/matrix-org/olm.git

      - name: Build Olm
        run: |
          cd olm
          mkdir -p build
          cd build
          cmake ../
          cmake --build . --config Release -j8

