name: nunchuk-ubuntu-x86_64

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ubuntu-24.04-apt-${{ runner.os }}-${{ hashFiles('**/dependencies.txt') }}
          restore-keys: |
            ubuntu-24.04-apt-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake \
                              g++ \
                              make \
                              ninja-build \
                              libboost-all-dev \
                              libzmq3-dev \
                              libevent-dev \
                              libdb++-dev \
                              sqlite3 \
                              libsqlite3-dev \
                              qtbase5-dev \
                              qtdeclarative5-dev \
                              qtquickcontrols2-5-dev \
                              qtmultimedia5-dev \
                              qttools5-dev \
                              qttools5-dev-tools \
                              libqt5svg5-dev \
                              libqt5networkauth5-dev \
                              libsecret-1-dev \
                              git \
                              dpkg-dev 
      
      - name: Build and Install qtkeychain
        working-directory: ${{ runner.workspace }}
        run: |
          git clone https://github.com/frankosterfeld/qtkeychain.git
          cd qtkeychain
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Checkout Olm
        working-directory: ${{ runner.workspace }}
        run: git clone https://gitlab.matrix.org/matrix-org/olm.git

      - name: Build Olm
        working-directory: ${{ runner.workspace }}/olm
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Checkout nunchuk-qt
        working-directory: ${{ runner.workspace }}
        env:
          GITLAB_PASS: ${{ secrets.GITLAB_PASS }}
        run: |
          echo -e "machine gitlab.com\n  login hadvluffy\n  password $GITLAB_PASS" > ~/.netrc
          chmod 600 ~/.netrc
          git clone -b do-group-wallet https://gitlab.com/nunchuck/nunchuck-qt nunchuk-qt --depth 1
          cd nunchuk-qt
          git submodule update --init --recursive

      - name: Remove default openssl
        run: |
          sudo mv /usr/include/x86_64-linux-gnu/openssl /usr/include/x86_64-linux-gnu/openssl_bak
          
      - name: Build openssl
        working-directory: ${{runner.workspace}}/nunchuk-qt/contrib/libnunchuk/contrib/openssl
        run: |
          source ~/.bashrc
          ./config --prefix="$PWD/lib"
          make -j$(nproc)
          make install_dev

      - name: Configure nunchuk-qt
        working-directory: ${{ runner.workspace }}/nunchuk-qt
        run: |
          mkdir -p build
          cd build
          export CC="gcc -no-pie"
          export CXX="g++ -no-pie"
          cmake .. -DCMAKE_BUILD_TYPE=Release -DUR__DISABLE_TESTS=ON

      - name: Build nunchuk-qt
        working-directory: ${{ runner.workspace }}/nunchuk-qt/build
        run: make -j$(nproc)

      - name: Check linked libraries
        working-directory: ${{ runner.workspace }}/nunchuk-qt/build
        run: |
          ldd ./nunchuk-qt || echo "Library dependencies check failed!"

      - name: Deploy to release folder
        working-directory: ${{ runner.workspace }}/nunchuk-qt/build
        run: |
          mkdir -p ${{ runner.workspace }}/nunchuk-qt-linux
          cp -r * ${{ runner.workspace }}/nunchuk-qt-linux
          echo "Deployment completed."

      - name: Create Debian package
        working-directory: ${{ runner.workspace }}/nunchuk-linux
        run: |
          mkdir -p DEBIAN
          echo "Package: nunchuk-qt" > DEBIAN/control
          echo "Version: 1.0" >> DEBIAN/control
          echo "Section: base" >> DEBIAN/control
          echo "Priority: optional" >> DEBIAN/control
          echo "Architecture: amd64" >> DEBIAN/control
          echo "Maintainer: Nunchuk Inc<contact@nunchuk.io>" >> DEBIAN/control
          echo "Description: Nunchuk Qt application" >> DEBIAN/control
          dpkg-shlibdeps -O ./nunchuk-qt >> DEBIAN/control
          dpkg-deb --build ${{ runner.workspace }}/nunchuk-linux nunchuk-qt.deb

      - name: Zip release package
        working-directory: ${{ runner.workspace }}
        run: |
          zip -r nunchuk-linux.zip nunchuk-linux
          echo "Release package created."

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nunchuk-linux
          path: |
            ${{ runner.workspace }}/nunchuk-qt.deb
            ${{ runner.workspace }}/nunchuk-linux.zip

