name: nunchuk-window-x86_64

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Check Windows Version
        run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
        shell: cmd

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          git checkout eb492805e92a2c14a230f5c3deb3e89f6771c321
          .\bootstrap-vcpkg.bat
        shell: powershell

      - name: Cache vcpkg dependencies
        uses: actions/cache@v4
        with:
          path: vcpkg/installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: vcpkg-${{ runner.os }}-

      #- name: Install dependencies (example: boost)
      #  run: |
      #    vcpkg\vcpkg.exe install boost
      #  shell: powershell

