name: nunchuk-window-x86_64

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: clear
  VCPKG_DEFAULT_TRIPLET: 'x64-windows'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            D:/a/vcpkg
            ~/.cache/vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Setup vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: 'D:/a/vcpkg'
          vcpkgGitCommitId: 'eb492805e92a2c14a230f5c3deb3e89f6771c321'

      - name: Install dependencies with vcpkg
        run: |
          vcpkg install boost:x64-windows \
                        zeromq:x64-windows \
                        libevent:x64-windows \
                        berkeleydb:x64-windows \
                        sqlite3:x64-windows \
                        sqlcipher:x64-windows \
                        qt5:x64-windows \
                        qt5-graphicaleffects:x64-windows \
                        qt5-quickcontrols:x64-windows \
                        qtKeychain:x64-windows
                        
          vcpkg integrate install

      - name: Checkout libolm
        working-directory: ${{ runner.workspace }}
        run: |
          git clone https://gitlab.matrix.org/matrix-org/olm --depth 1
          cd olm
          git submodule update --init --recursive
