name: nunchuk-window-x86_64

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Check Windows Version
        shell: pwsh
        run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
        with:
            msbuild-architecture: x64

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install aqtinstall
        run: |
          pip install aqtinstall
  
      - name: Install Qt 5.15.2 (MSVC 2019)
        run: |
          aqt list-qt windows desktop --modules 5.15.2 win64_msvc2019_64
          aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 --outputdir C:\qt --archives
          aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 `
                      --outputdir C:\qt `
                      -m `
                      qtcharts `
                      qtdatavis3d `
                      qtlottie `
                      qtnetworkauth `
                      qtpurchasing `
                      qtquick3d `
                      qtquicktimeline `
                      qtscript `
                      qtvirtualkeyboard `
                      qtwebengine `
                      qtwebglplugin `
                      debug_info
          Write-Host "Qt installed at: $qtPath\windows\desktop\$qtVersion\msvc2019_64"
      
      - name: Print Qt installation path
        run: |
          echo "Qt installed at: C:\qt\5.15.2\msvc2019_64"
          dir C:\qt\5.15.2\msvc2019_64
          dir C:\qt\5.15.2\msvc2019_64\bin
      
      - name: Set Qt env
        run: |
          echo "QT_DIR=C:\qt\5.15.2\msvc2019_64" >> $GITHUB_ENV
