name: nunchuk-window-x86_64

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Check Windows Version
        shell: pwsh
        run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
        with:
            msbuild-architecture: x64

      - name: Install CMake 3.31.0
        shell: pwsh
        run: |
          $version = "3.31.0"
          $uri = "https://github.com/Kitware/CMake/releases/download/v$version/cmake-$version-windows-x86_64.zip"
          $zipPath = "$env:TEMP\cmake.zip"
          $cmakeDir = "$env:ProgramFiles\CMake"
      
          Invoke-WebRequest -Uri $uri -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $cmakeDir -Force
      
          $binPath = "$cmakeDir\cmake-$version-windows-x86_64\bin"
          echo "$binPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Check CMake version
        run: cmake --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install aqtinstall
        run: |
          pip install aqtinstall
  
      - name: Install Qt 5.15.2 (MSVC 2019)
        run: |
          aqt list-qt windows desktop --modules 5.15.2 win64_msvc2019_64
          aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 --outputdir C:\qt
          aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 --outputdir C:\qt -m 
                                                                                      qtcharts `
                                                                                      qtdatavis3d `
                                                                                      qtlottie `
                                                                                      qtnetworkauth `
                                                                                      qtpurchasing `
                                                                                      qtquick3d `
                                                                                      qtquicktimeline `
                                                                                      qtscript `
                                                                                      qtvirtualkeyboard `
                                                                                      qtwebengine `
                                                                                      qtwebglplugin `
                                                                                      debug_info
                                                                  
          Write-Host "Qt installed at: $qtPath\windows\desktop\$qtVersion\msvc2019_64"
      
      - name: Print Qt installation path
        run: |
          echo "Qt installed at: C:\qt\5.15.2\msvc2019_64"
          dir C:\qt\5.15.2\msvc2019_64
          dir C:\qt\5.15.2\msvc2019_64\bin
          echo "QT_DIR=C:\qt\5.15.2\msvc2019_64" >> $GITHUB_ENV
      
      - name: Setup Cache vcpkg packages
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.workspace }}/vcpkg
            ${{ runner.workspace }}/vcpkg/installed
          key: vcpkg-full-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-full-${{ runner.os }}-

      - name: Set up vcpkg
        working-directory: ${{ runner.workspace }}
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          echo "Checkout version f523208df4ae467436dc2d2eeab594fed240d552"
          git checkout f523208df4ae467436dc2d2eeab594fed240d552
          .\bootstrap-vcpkg.bat
          
      - name: Install dependencies with vcpkg
        working-directory: ${{ runner.workspace }}
        shell: pwsh
        run: |
          vcpkg\vcpkg.exe install boost:x64-windows `
                                  zeromq:x64-windows `
                                  libevent:x64-windows `
                                  berkeleydb:x64-windows `
                                  sqlite3:x64-windows `
                                  sqlcipher:x64-windows
                        
          vcpkg\vcpkg.exe integrate install
          vcpkg\vcpkg.exe list

      - name: Checkout Olm
        working-directory: ${{ runner.workspace }}
        run: git clone https://gitlab.matrix.org/matrix-org/olm.git
      
      - name: Build Olm
        working-directory: ${{ runner.workspace }}/olm
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          
      - name: Checkout QtKeychain
        working-directory: ${{ runner.workspace }}
        run: |
          git clone https://github.com/frankosterfeld/qtkeychain.git
      
      - name: Build QtKeychain
        working-directory: ${{ runner.workspace }}/qtkeychain
        run: |
          cmake -B build -S . `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake `
            -DVCPKG_TARGET_TRIPLET=x64-windows `
            -DCMAKE_INSTALL_PREFIX="C:/qtkeychainInstalled" `
            -DQt5_DIR="C:\Qt\5.15.2\msvc2019_64\lib\cmake\Qt5"
            
          cmake --build build --config Release
          cmake --install build --config Release
          echo "QTKEYCHAIN_PATH=C:/qtkeychainInstalled" >> $GITHUB_ENV
          
      - name: Checkout nunchuk-qt
        working-directory: ${{ runner.workspace }}
        env:
          GITLAB_PASS: ${{ secrets.GITLAB_PASS }}
        shell: pwsh
        run: |
          # Tạo ~/.netrc
          $netrcContent = "machine gitlab.com`n  login hadvluffy`n  password $env:GITLAB_PASS"
          $netrcPath = "$env:USERPROFILE\.netrc"
          $netrcContent | Out-File -FilePath $netrcPath -Encoding ASCII
      
          # Set biến môi trường
          $env:TARGET_BRANCH = "fixbug"
          echo "BUILD_BRANCH=$env:TARGET_BRANCH" >> $env:GITHUB_ENV
      
          echo "Cloning fresh repository"
          if (Test-Path "nunchuk-qt") { Remove-Item -Recurse -Force "nunchuk-qt" }
          git clone -b $env:TARGET_BRANCH https://gitlab.com/nunchuck/nunchuck-qt nunchuk-qt
          Set-Location nunchuk-qt
          git fetch --all --tags --force
          git submodule sync --recursive
          git submodule update --init --recursive
      
          $lastCommit = git rev-parse HEAD
          echo "Latest commit ----->>>>> $lastCommit"
          echo "LAST_COMMITID=$lastCommit" >> $env:GITHUB_ENV
      
          $latestTag = git for-each-ref --sort=-taggerdate --format '%(refname:short)' refs/tags | Select-Object -First 1
          $currentCommit = git rev-parse HEAD
          $taggedCommit = git rev-list -n 1 $latestTag
          echo "Latest tag found: $latestTag (commit $taggedCommit)"
          echo "Current commit: $currentCommit"
          echo "LATEST_VERSION=$latestTag" >> $env:GITHUB_ENV
      
      - name: Generate build timestamp
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          echo "Timestamp: $timestamp"
          echo "TIMESTAMP=$timestamp" >> $env:GITHUB_ENV

      - name: Check environment variants
        id: set-timestamp
        run: |
          echo "Timestamp build :>>> ${{ env.TIMESTAMP }}"
          echo "Version target build :>>> ${{ env.LATEST_VERSION }}"
          echo "Commit target build :>>> ${{ env.LAST_COMMITID }}"
          echo "Branch target build :>>> ${{ env.BUILD_BRANCH }}"
          
      - name: Configuration nunchuk-qt
        shell: pwsh
        env:
          toolchainFile: C:\a\macdeploynunchuk\vcpkg\scripts\buildsystems\vcpkg.cmake
          project_path: ${{ runner.workspace }}\nunchuk-qt
          build_mode: Release
        run: |
          $qtDir = ${{ env.QT_DIR }}
          $qtKeychain = ${{ env.QTKEYCHAIN_PATH }}
          echo "Qt path :>>> $qtDir"
          echo "Qt keychain path :>>> $qtKeychain"
          
          $cmakeConfigureCmd = @(
            "-G", "Visual Studio 16 2019",
            "-A", "x64",
            "-B", "build",
            "-S", "$env:project_path",
            "-DCMAKE_BUILD_TYPE=$env:build_mode",
            "-DCMAKE_TOOLCHAIN_FILE=$env:toolchainFile",
            "-DVCPKG_TARGET_TRIPLET=x64-windows",
            "-DUR__DISABLE_TESTS=ON",
            "-DQt5_DIR=C:\qt\5.15.2\msvc2019_64\lib\cmake\Qt5",
            "-DCMAKE_PREFIX_PATH=C:\qtkeychainInstalled",
            "-D_WIN32_WINNT=0x0601"
          )
          cmake @cmakeConfigureCmd
          
      - name: Build nunchuk-qt
        shell: pwsh
        env:
          build_mode: Release
        run: |
          $cmakeBuildCmd = @(
            "--build", 
            "build", 
            "--config", 
            "$env:build_mode", 
            "--", 
            "/m:4"
          )
          cmake @cmakeBuildCmd



